# Generated by Django 3.2.4 on 2021-06-28 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('num_hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebHookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.TextField(default=None, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookdata',
            index=models.Index(fields=['received_at'], name='core_webhoo_receive_672f94_idx'),
        ),
    ]
