# Generated by Django 3.2.4 on 2021-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_endpoint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookdata',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='headers',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='query_params',
            field=models.TextField(default=None, null=True),
        ),
    ]
