# Generated by Django 3.2.4 on 2021-06-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210630_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdata',
            name='endpoint_hit_number',
            field=models.IntegerField(default=0),
        ),
    ]
