# Generated by Django 3.2.4 on 2021-07-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_webhookdata_endpoint_hit_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
